# ==================== 针对 Zephyr 4.4.1 的全量完全体显示驱动配置 ====================
CONFIG_GPIO=y
CONFIG_I2C=y

# 1. 激活 Zephyr 内核的总显示模块接口
CONFIG_DISPLAY=y

# 2. 【核心修复】显式将 ssd1306 的物理驱动源码打包进编译树
CONFIG_SSD1306=y

# 3. 激活基于字符的帧缓冲区
CONFIG_CHARACTER_FRAMEBUFFER=y

# 4. 现代电源管理支持
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_HEAP_MEM_POOL_SIZE=4096
# ==================== 追加：开启更小尺寸的内置字库支持 ====================
# 激活全行业最紧凑的 8x8 像素字库（支持垂直方向排满 8 行文本）
# CONFIG_CFB_FONTS_ENABLE=y
# CONFIG_CFB_FONT_8X8=y
# LIS3DSH（三轴加速度计）驱动与中断线程配置
# CONFIG_SENSOR=y
#-CONFIG_LIS3DSH=y
#-CONFIG_LIS3DSH_TRIGGER_OWN_THREAD=y
